[tool.poetry]
name = "yt-downloader"
version = "0.1.0"
description = "Desktop shell for probing YouTube metadata and media qualities."
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
yt-dlp = "2026.3.17"
pywebview = "^6.2.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
packaging = [
    "pyinstaller (>=6.16.0,<7.0.0)"
]
